"""Pure-Python prediction objects generated by CASE model training."""

from __future__ import annotations

from dataclasses import dataclass
import math
from numbers import Real
from statistics import median
from typing import Mapping, Protocol, Sequence


class ArousalPredictor(Protocol):
    """Small interface shared by fitted and personally calibrated models."""

    feature_names: tuple[str, ...]

    def predict(self, features: Mapping[str, float]) -> float: ...


def _feature_vector(feature_names: tuple[str, ...], features: Mapping[str, float]) -> tuple[float, ...]:
    if not isinstance(features, Mapping):
        raise TypeError("features must be a mapping of feature names to numbers")
    expected = set(feature_names)
    supplied = set(features)
    missing = sorted(expected - supplied)
    extra = sorted(supplied - expected)
    if missing or extra:
        details: list[str] = []
        if missing:
            details.append(f"missing={missing}")
        if extra:
            details.append(f"extra={extra}")
        raise ValueError("Invalid feature names: " + ", ".join(details))
    values: list[float] = []
    for name in feature_names:
        value = features[name]
        if isinstance(value, bool) or not isinstance(value, Real):
            raise TypeError(f"Feature {name!r} must be numeric")
        numeric = float(value)
        if not math.isfinite(numeric):
            raise ValueError(f"Feature {name!r} must be finite")
        values.append(numeric)
    return tuple(values)


def _validate_model_header(
    feature_names: tuple[str, ...], metrics: dict[str, float], metadata: dict[str, object]
) -> None:
    if not feature_names or len(set(feature_names)) != len(feature_names):
        raise ValueError("feature_names must be non-empty and unique")
    if not isinstance(metrics, dict) or not isinstance(metadata, dict):
        raise TypeError("metrics and metadata must be dictionaries")


@dataclass(frozen=True)
class ArousalModel:
    """A fitted Ridge model retained as the transparent linear baseline."""

    feature_names: tuple[str, ...]
    coefficients: tuple[float, ...]
    intercept: float
    alpha: float
    metrics: dict[str, float]
    metadata: dict[str, object]

    def __post_init__(self) -> None:
        _validate_model_header(self.feature_names, self.metrics, self.metadata)
        if len(self.feature_names) != len(self.coefficients):
            raise ValueError("feature_names and coefficients must have equal length")
        numeric = (*self.coefficients, self.intercept, self.alpha)
        if not all(math.isfinite(float(value)) for value in numeric):
            raise ValueError("model parameters must be finite")
        if self.alpha < 0:
            raise ValueError("alpha cannot be negative")

    def predict(self, features: Mapping[str, float]) -> float:
        values = _feature_vector(self.feature_names, features)
        prediction = float(self.intercept)
        for coefficient, value in zip(self.coefficients, values, strict=True):
            prediction += float(coefficient) * value
        return float(prediction)


@dataclass(frozen=True)
class DecisionTreeModel:
    """Compact arrays for one fitted regression tree."""

    children_left: tuple[int, ...]
    children_right: tuple[int, ...]
    feature_indices: tuple[int, ...]
    thresholds: tuple[float, ...]
    values: tuple[float, ...]

    def __post_init__(self) -> None:
        lengths = {
            len(self.children_left),
            len(self.children_right),
            len(self.feature_indices),
            len(self.thresholds),
            len(self.values),
        }
        if lengths == {0} or len(lengths) != 1:
            raise ValueError("tree arrays must be non-empty and have equal lengths")

    def predict_vector(self, features: tuple[float, ...]) -> float:
        node = 0
        for _ in range(len(self.values) + 1):
            left = self.children_left[node]
            if left < 0:
                return float(self.values[node])
            feature_index = self.feature_indices[node]
            if not 0 <= feature_index < len(features):
                raise ValueError("tree contains an invalid feature index")
            if features[feature_index] <= self.thresholds[node]:
                node = left
            else:
                node = self.children_right[node]
        raise ValueError("tree traversal did not reach a leaf")


@dataclass(frozen=True)
class RandomForestModel:
    feature_names: tuple[str, ...]
    trees: tuple[DecisionTreeModel, ...]
    metrics: dict[str, float]
    metadata: dict[str, object]

    def __post_init__(self) -> None:
        _validate_model_header(self.feature_names, self.metrics, self.metadata)
        if not self.trees:
            raise ValueError("RandomForestModel needs at least one tree")

    def predict(self, features: Mapping[str, float]) -> float:
        values = _feature_vector(self.feature_names, features)
        return float(sum(tree.predict_vector(values) for tree in self.trees) / len(self.trees))


@dataclass(frozen=True)
class GradientBoostingModel:
    feature_names: tuple[str, ...]
    initial_prediction: float
    learning_rate: float
    trees: tuple[DecisionTreeModel, ...]
    metrics: dict[str, float]
    metadata: dict[str, object]

    def __post_init__(self) -> None:
        _validate_model_header(self.feature_names, self.metrics, self.metadata)
        if not self.trees:
            raise ValueError("GradientBoostingModel needs at least one tree")
        if not math.isfinite(self.initial_prediction) or not self.learning_rate > 0:
            raise ValueError("invalid gradient-boosting parameters")

    def predict(self, features: Mapping[str, float]) -> float:
        values = _feature_vector(self.feature_names, features)
        prediction = self.initial_prediction
        for tree in self.trees:
            prediction += self.learning_rate * tree.predict_vector(values)
        return float(prediction)


@dataclass(frozen=True)
class RbfSvrModel:
    feature_names: tuple[str, ...]
    scaler_mean: tuple[float, ...]
    scaler_scale: tuple[float, ...]
    support_vectors: tuple[tuple[float, ...], ...]
    dual_coefficients: tuple[float, ...]
    intercept: float
    gamma: float
    metrics: dict[str, float]
    metadata: dict[str, object]

    def __post_init__(self) -> None:
        _validate_model_header(self.feature_names, self.metrics, self.metadata)
        width = len(self.feature_names)
        if len(self.scaler_mean) != width or len(self.scaler_scale) != width:
            raise ValueError("SVR scaler dimensions do not match feature_names")
        if len(self.support_vectors) != len(self.dual_coefficients) or not self.support_vectors:
            raise ValueError("SVR support-vector dimensions are invalid")
        if any(len(vector) != width for vector in self.support_vectors):
            raise ValueError("SVR support vectors have the wrong width")
        if any(scale <= 0 or not math.isfinite(scale) for scale in self.scaler_scale):
            raise ValueError("SVR scaler values must be positive and finite")
        if self.gamma <= 0 or not math.isfinite(self.gamma):
            raise ValueError("SVR gamma must be positive and finite")

    def predict(self, features: Mapping[str, float]) -> float:
        raw = _feature_vector(self.feature_names, features)
        scaled = tuple(
            (value - mean) / scale
            for value, mean, scale in zip(raw, self.scaler_mean, self.scaler_scale, strict=True)
        )
        prediction = float(self.intercept)
        for coefficient, support_vector in zip(
            self.dual_coefficients, self.support_vectors, strict=True
        ):
            squared_distance = sum(
                (value - support) ** 2
                for value, support in zip(scaled, support_vector, strict=True)
            )
            prediction += coefficient * math.exp(-self.gamma * squared_distance)
        return float(prediction)


@dataclass(frozen=True)
class EnsembleArousalModel:
    """Fixed weighted average of fitted models sharing one input contract."""

    feature_names: tuple[str, ...]
    models: tuple[ArousalPredictor, ...]
    weights: tuple[float, ...]
    metrics: dict[str, float]
    metadata: dict[str, object]

    def __post_init__(self) -> None:
        _validate_model_header(self.feature_names, self.metrics, self.metadata)
        if not self.models or len(self.models) != len(self.weights):
            raise ValueError("Ensemble models and weights must be non-empty and equal length")
        if any(model.feature_names != self.feature_names for model in self.models):
            raise ValueError("Every ensemble component must use the same feature names")
        if any(not math.isfinite(weight) or weight < 0 for weight in self.weights):
            raise ValueError("Ensemble weights must be finite and non-negative")
        if not math.isclose(sum(self.weights), 1.0, rel_tol=1e-12, abs_tol=1e-12):
            raise ValueError("Ensemble weights must sum to one")

    def predict(self, features: Mapping[str, float]) -> float:
        return float(
            sum(
                weight * model.predict(features)
                for weight, model in zip(self.weights, self.models, strict=True)
            )
        )


@dataclass(frozen=True)
class PersonalizedArousalModel:
    """A base model plus one strongly regularized participant-specific offset."""

    base_model: ArousalPredictor
    offset: float
    calibration_count: int
    prior_strength: float
    minimum_rating: float = 0.5
    maximum_rating: float = 9.5

    def __post_init__(self) -> None:
        if self.calibration_count < 3:
            raise ValueError("Personal calibration requires at least three examples")
        numeric = (
            self.offset,
            self.prior_strength,
            self.minimum_rating,
            self.maximum_rating,
        )
        if not all(math.isfinite(float(value)) for value in numeric):
            raise ValueError("Calibration parameters must be finite")
        if self.prior_strength <= 0:
            raise ValueError("prior_strength must be positive")
        if self.minimum_rating >= self.maximum_rating:
            raise ValueError("minimum_rating must be below maximum_rating")

    @property
    def feature_names(self) -> tuple[str, ...]:
        return self.base_model.feature_names

    def predict(self, features: Mapping[str, float]) -> float:
        prediction = float(self.base_model.predict(features)) + self.offset
        return float(min(self.maximum_rating, max(self.minimum_rating, prediction)))


def calibrate_personal_model(
    base_model: ArousalPredictor,
    calibration_examples: Sequence[tuple[Mapping[str, float], float]],
    *,
    prior_strength: float = 10.0,
    max_abs_offset: float = 1.0,
    minimum_rating: float = 0.5,
    maximum_rating: float = 9.5,
) -> PersonalizedArousalModel:
    """Fit only a robust, shrunk offset from three or more personal ratings.

    No slope or physiological coefficient is changed. Examples should come from
    distinct, non-overlapping situations to avoid temporal leakage.
    """

    examples = list(calibration_examples)
    if len(examples) < 3:
        raise ValueError("Provide at least three personal calibration examples")
    if not math.isfinite(prior_strength) or prior_strength <= 0:
        raise ValueError("prior_strength must be positive and finite")
    if not math.isfinite(max_abs_offset) or max_abs_offset <= 0:
        raise ValueError("max_abs_offset must be positive and finite")
    if not minimum_rating < maximum_rating:
        raise ValueError("minimum_rating must be below maximum_rating")

    residuals: list[float] = []
    for features, actual_rating in examples:
        if isinstance(actual_rating, bool) or not isinstance(actual_rating, Real):
            raise TypeError("Calibration ratings must be numeric")
        rating = float(actual_rating)
        if not math.isfinite(rating) or not minimum_rating <= rating <= maximum_rating:
            raise ValueError(
                f"Calibration ratings must be between {minimum_rating} and {maximum_rating}"
            )
        residuals.append(rating - float(base_model.predict(features)))

    robust_residual = float(median(residuals))
    weight = len(residuals) / (len(residuals) + float(prior_strength))
    offset = min(max_abs_offset, max(-max_abs_offset, weight * robust_residual))
    return PersonalizedArousalModel(
        base_model=base_model,
        offset=float(offset),
        calibration_count=len(examples),
        prior_strength=float(prior_strength),
        minimum_rating=float(minimum_rating),
        maximum_rating=float(maximum_rating),
    )


AnyArousalModel = (
    ArousalModel
    | RandomForestModel
    | GradientBoostingModel
    | RbfSvrModel
    | EnsembleArousalModel
    | PersonalizedArousalModel
)
