"""Generated by eurisko_overspending.training. Do not edit manually."""

from eurisko_overspending.model import OverspendingModel


model = OverspendingModel(
    intercept=-2.546953551445,
    coefficients={
        "z_ib": 0.786630129324,
        "p_d": 5.490348683030,
        "p_w": 0.120199398681,
        "p_m": -0.162959304691,
    },
    threshold=0.5,
)
